name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'

      - name: Install npm packages and build
        run: |
          npm install -g @angular/cli
          npm install
          npm run build:prod

      # Copy index.html to 404.html to serve the same file when a file is not found.
      - name: Copy index.html to 404.html
        run: cp dist/text-morph/index.html dist/text-morph/404.html

      # Add .nojekyll file so GitHub pages doesn't treat this project as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch dist/text-morph/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist/text-morph
