name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup Node.js
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install and Build 🔧
        run: |
          npm install
          npm test
          npm run build:prod

      # Change the base-tag in index.html from '/' to '/app-name' to match GitHub Pages repository subdirectory.
      - name: Change base-tag in index.html
        run: sed -i 's/<base href="\/" \/>/<base href="\/text-morph\/" \/>/g' dist/text-morph/index.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist/text-morph
